### ISSUE TITLE
Minecraft Crash

### ISSUE THREAD

**Issue by BlueMalarkey62** [tired9494/Flight-Rings#8]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/15/22, 1:40 AM
Description: Exception in server tick loop

java.lang.AbstractMethodError: Receiver class github.tired9494.flight_rings.config.FlightRingsConfig$$Lambda$3467/0x00000001009bcb78 does not define or inherit an implementation of the resolved method 'abstract void startDataPackReload(net.minecraft.server.MinecraftServer, net.minecraft.class_6860)' of interface net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents$StartDataPackReload.
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$8(ServerLifecycleEvents.java:84)
	at net.minecraft.server.MinecraftServer.handler$zfm000$startResourceReload(MinecraftServer.java:2852)
	at net.minecraft.server.MinecraftServer.method_29439(MinecraftServer.java)
	at net.minecraft.class_3097.method_29480(class_3097.java:22)
	at net.minecraft.class_3097.method_13530(class_3097.java:53)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
	at net.minecraft.class_2170.method_9249(class_2170.java:264)
	at net.minecraft.class_3244.method_14370(class_3244.java:1253)
	at net.minecraft.class_3244.method_31286(class_3244.java:1237)
	at net.minecraft.class_3244.method_12048(class_3244.java:1220)
	at net.minecraft.class_2797.method_12115(class_2797.java:30)
	at net.minecraft.class_2797.method_11054(class_2797.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:40)
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:198)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165)
	at net.minecraft.class_1255.method_16075(class_1255.java:163)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784)
	at net.minecraft.class_1255.method_18857(class_1255.java:176)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 631410208 bytes (602 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.19
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a56
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8681
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 18632.94
	Virtual memory used (MB): 10547.32
	Swap memory total (MB): 10752.00
	Swap memory used (MB): 1369.35
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bedrockify: BedrockIfy 1.4.1+mc1.18.2
		blue_endless_jankson: jankson 1.2.1
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		diggusmaximus: Diggus Maximus 1.5.4-1.18
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		fabric: Fabric API 0.47.10+1.18.2
		fabric-api-base: Fabric API Base 0.4.3+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.6+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.2+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.11+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.8+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.7+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.20+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.1+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.10+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.16+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.7+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.18+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.12+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.12+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.2+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.9+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.11+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.9+b4f4f6cd60
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.1+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.10+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.3+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.5+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.20+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.7+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.2+34b2a0ce60
		fabric-particles-v1: Fabric Particles (v1) 0.2.11+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.7+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.12+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.16+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.6+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.1+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.1+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.17+801ec85b60
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.9+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.13+d7c144a860
		fabric-textures-v0: Fabric Textures (v0) 1.0.11+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.13+cca23f9360
		fabricloader: Fabric Loader 0.13.3
		flight_rings: Flight Rings 1.6.2
		java: OpenJDK 64-Bit Server VM 17
		kyrptconfig: Kyrpt Config 1.4.1-1.18
		magic_mirror: Magic Mirror 1.3.4b
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		optifabric: OptiFabric 1.13.0
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.3.0
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.1-1.18.1
		worldedit: WorldEdit 7.2.10+1742f98
		xaerominimap: Xaero's Minimap 22.5.0
		xaeroworldmap: Xaero's World Map 1.20.6
	Server Running: true
	Player Count: 1 / 8; [class_3222['SatoSereMXN'/199, l='ServerLevel[HARDCORE DAB LIT FAM DAB]', x=-184.54, y=20.00, z=62.42]]
	Data Packs: vanilla, file/wither-combined-v1-0-0.zip (incompatible), Fabric Mods, file/herobrine_datapack (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	OptiFine Version: OptiFine_1.18.2_HD_U_H7
	OptiFine Build: 20220410-185216
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 - Build 27.20.100.8681
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.18.2
	OptiFine jar version: OptiFine_1.18.2_HD_U_H7
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/Ric/AppData/Roaming/.minecraft/.optifine/OptiFine_1.18.2_HD_U_H7/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by tired9494** [comment]
was this caused by running /reload?
